### ISSUE TITLE
Icon not loading

### ISSUE THREAD

**Issue by Robvred** [mozziemozz/home-assistant-svg-file-loader#3]
Hello !

Thanks to you and your brother for this awesome stuff !

I'm not able to load my svg icon, I've tried with many other svg and it's same. When I start typing I can see the fallback icon so module is well installed.
As the name is correct, fallback icon disappear but nothing appear.

Do you have any idea ?

**Comment by mozziemozz** [comment]
Have you tried restarting your Home Assistant? You can also try to use Developer Mode by pressing F12 and disable cache mode. It took some time on my installation until the icons were displayed correctly aswell.

**Comment by mozziemozz** [comment]
Have you tried restarting your Home Assistant? You can also try to use Developer Mode by pressing F12 and disable cache mode. It took some time on my installation until the icons appeared as well.

**Comment by retoheusser** [comment]
Additionally the loading mechanism won't work if you're using Internet Explorer or another ancient browser.
The minimum required home assistant version is 0.110 as per https://developers.home-assistant.io/blog/2020/05/09/custom-iconsets/. This project doesn't support older versions.

**Comment by Robvred** [comment]
> Have you tried restarting your Home Assistant? You can also try to use Developer Mode by pressing F12 and disable cache mode. It took some time on my installation until the icons appeared as well.

Sure tried many times, and cache flushed.

> Additionally the loading mechanism won't work if you're using Internet Explorer or another ancient browser.
> The minimum required home assistant version is 0.110 as per https://developers.home-assistant.io/blog/2020/05/09/custom-iconsets/. This project doesn't support older versions.

My instance is updated with the 2021.1.4 and I've tried with Brave and Safari.

@retoheusser @mozziemozz Do you know or did you already tried with colored icon for exemple download from flaticon.com.
It's seems when many patch are present in the svg it's not compatible, are you able to confirm that ? or did you resize and minify the svg before your import ?

**Comment by mozziemozz** [comment]
No, I didn't try colored icons as my goal for the color was to be changed according to the entity's state in HA.
I used the SVG files from here: https://github.com/prasertcbs/HueIconPackPng
You could try to extract the path part from one of your Icons and replace the fallback icon's path in the JS file and see if it loads.
Otherwise I suggest that you try to adjust your SVGs so that they are like the ones from the link above. I am no SVG expert but I believe that the Icon Size has to be 32x32 pixels. The Icons I use contain the following code:

svg width="32px" height="32px" viewBox="0 0 32 32"

In our file-loader.js we also use the same viewBox:

viewBox: "0 0 32 32"

I hope that helps.

**Comment by dUaL13** [comment]
Hello, 

Thanks for your work ! 

I have the exact same issue as Robvred, I also tried to delete cache and restart HA but nothing appears when I finished to type the name. I have the latest version of HA and using Firefox and Chrome. I tried with the icons located at https://github.com/prasertcbs/HueIconPackPng and some customs of mine but the problem is the same. I don't know what other tests can I do ?

**Comment by mozziemozz** [comment]
Did you overwrite the icon directly in in lovelace or did you overwrite it using customize.yaml?

**Comment by mozziemozz** [comment]
I first tried it with this Icon Set: https://github.com/XusBadia/zeus-icon-set-ha
It works a little bit different because all the SVG Icons in this Custom Icon set are embedded inline in the JS File. You could also try to install this icon set and see if these icons load.

Because I wanted to use my own custom icons, we created this svg icon file loader for HA. Are you sure your icons are located at \\your HA IP\config\www\svg ?

**Comment by Robvred** [comment]
Hello @dUaL13,

Try to use https://jakearchibald.github.io/svgomg/ with basics option, but imperatively use 
<img width="339" alt="Capture d’écran 2021-01-24 à 20 32 52" src="https://user-images.githubusercontent.com/12579254/105641277-5a153c80-5e83-11eb-89e9-7fb9acf7a0a1.png">

That's can solve your problems, but unfortunately no founded scripts work with colorized icons.

**Comment by mozziemozz** [comment]
Home Assistant only uses MDI Icons by default. These are all not in color. I believe that it's just how HA works and can't be changed easily. But you could always use entity_picture: to load other image files. 
Let me know if you got it working with the example icon pack I linked in my earlier comment. It works for me with the latest HA version and displayes correctly in Edge (Chromium) and even the mobile app.

**Comment by dUaL13** [comment]
> 
> 
> Did you overwrite the icon directly in in lovelace or did you overwrite it using customize.yaml?

I tried both ways, but neither worked.

> 
> 
> I first tried it with this Icon Set: https://github.com/XusBadia/zeus-icon-set-ha
> It works a little bit different because all the SVG Icons in this Custom Icon set are embedded inline in the JS File. You could also try to install this icon set and see if these icons load.
> 
> Because I wanted to use my own custom icons, we created this svg icon file loader for HA. Are you sure your icons are located at \your HA IP\config\www\svg ?

I tried this icons set and it is functionnal, thanks by the way, I was not aware of these extra icons !

> 
> 
> Hello @dUaL13,
> 
> Try to use https://jakearchibald.github.io/svgomg/ with basics option, but imperatively use
> <img alt="Capture d’écran 2021-01-24 à 20 32 52" width="339" src="https://user-images.githubusercontent.com/12579254/105641277-5a153c80-5e83-11eb-89e9-7fb9acf7a0a1.png">
> 
> That's can solve your problems, but unfortunately no found scripts work with colorized icons.

**And this finally solve the problem !!** After converting my icons they are now visible with "file:icon_name". And the color based on state is also working !

Thank you all for your answers and links !! I had been stuck on this problem for a while.

**Comment by mozziemozz** [comment]
No worries, glad it worked as you wanted it to in the end.
